[package]
name = "vicky-store"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap = "0.7.0"
simd-itertools = "0.2.3"
siphasher = "1.0.1"

[dev-dependencies]
rand = "0.8.5"

[workspace]
members = [
    "simulator"
]
