name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --release --verbose -- --nocapture
    - name: Run simple example
      run: cargo run --example simple
    - name: Run multithreaded example
      run: cargo run --example multithreaded
    - name: Run collections example
      run: cargo run --example collections
    - name: Run typed example
      run: cargo run --example typed
