name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --release --verbose -- --nocapture
    - name: Run simple example
      run: cargo run --example simple
    - name: Run multithreaded example
      run: cargo run --example multithreaded
    - name: Run lists example
      run: cargo run --example lists
    - name: Run typed example
      run: cargo run --example typed
    - name: Run perftest
      run: cargo -Z unstable-options -C candy-perf run --release
    - name: Run crasher
      run: cargo -Z unstable-options -C candy-crasher run --release
    - name: Run longliving
      run: cargo -Z unstable-options -C candy-longliving run --release -- 10 40001 10000
    - name: Run mini-candy
      run: cargo -Z unstable-options -C mini-candy run
    - name: Run test-list-collisions
      run: cargo -Z unstable-options -C test-list-collisions run --release
